nexus_config_docker: true
nexus_timezone: Europe/Berlin
nexus_admin_password: "admin"
nexus_anonymous_access: false
nexus_min_heap_size: "1200M"
nexus_max_heap_size: "4G"
nexus_max_direct_memory: "2G"
nexus_delete_default_repos: true
nexus_delete_default_blobstore: true
nexus_blobstores:
- name: docker-blobstore
  type: file
  path: /var/nexus/blobs/docker
- name: maven-blobstore
  type: file
  path: /var/nexus/blobs/maven
nexus_repos_docker_hosted:
# docker.lbwl.luxor.cloud
- name: lbwl-docker-releases
  v1_enabled: True
  http_port: 9337
  blob_store: docker-blobstore
nexus_repos_docker_proxy:
- name: docker-hub
  v1_enabled: True
  index_type: "HUB"
  remote_url: "https://registry-1.docker.io"
# Maven
nexus_repos_maven_proxy:
- name: maven-central
  remote_url: 'https://repo1.maven.org/maven2/'
  layout_policy: permissive
nexus_repos_maven_hosted:
- name: lbwl-mvn-releases
  version_policy: release
  blob_store: maven-blobstore
  write_policy: allow_once
- name: lbwl-mvn-snapshots
  version_policy: snapshot
  write_policy: allow_once
  blob_store: maven-blobstore
nexus_privileges:
# LBWL releases
- name: lbwl-mvn-releases-read
  description: 'Read and browse LBWL release repos'
  type: repository-view
  repository: lbwl-mvn-releases
  format: maven2
  actions:
  - read
  - browse
- name: lbwl-mvn-releases-deploy
  description: 'Deploy privileges for LBWL release repo'
  type: repository-view
  repository: lbwl-mvn-releases
  format: maven2
  actions:
  - read
  - browse
  - add
  - edit
# LBWL snapshots
- name: lbwl-mvn-snapshots-read
  description: 'Read and browse LBWL snapshot repo'
  type: repository-view
  repository: lbwl-mvn-snapshots
  format: maven2
  actions:
  - read
  - browse
- name: lbwl-mvn-snapshots-deploy
  description: 'Deploy privileges for LBWL snapshot repo'
  type: repository-view
  repository: lbwl-mvn-snapshots
  format: maven2
  actions:
  - read
  - browse
  - add
  - edit
nexus_roles:
- id: lbwl-devs
  name: lbwl-developers
  description: 'LBWL developers'
  privileges:
  - lbwl-mvn-releases-read
  - lbwl-mvn-snapshots-read
  - lbwl-mvn-snapshots-deploy
- id: lbwl-deployment
  name: lbwl-deployment
  description: 'LBWL deployment user'
  privileges:
  - lbwl-mvn-releases-deploy
nexus_local_users:
- username: lbwl-deploy
  state: present
  first_name: lbwl
  last_name: deployment
  email: lbwl.deployment@luxor.cloud
  password: "lol"
  roles:
  - lbwl-deployment
